name: Build Friends Zone APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set up Java Environment
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'any'
          channel: 'stable'

      - name: Fix Android Directory if Missing
        run: |
          cd fz_app
          if [ ! -d "android" ]; then
            flutter create . --org com.example --platforms=android
          fi

      - name: Get Dependencies and Build APK
        run: |
          cd fz_app
          flutter pub get
          flutter build apk --release --no-pub

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: fz_app/build/app/outputs/flutter-apk/app-release.apk
