name: Build Flutter APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set up Java Environment
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Install Dependencies
        run: |
          cd fz_app
          flutter pub get

      - name: Build Release APK Directly
        run: |
          cd fz_app
          flutter build apk --release --no-pub --target-platform android-arm,android-arm64,android-x64

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: fz_app/build/app/outputs/flutter-apk/app-release.apk
